//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.02 at 08:45:18 AM IST 
//


package com.manash.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.manash.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PorcheseOrder_QNAME = new QName("", "porchese-Order");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.manash.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PurchaseOrderType }
     * 
     */
    public PurchaseOrderType createPurchaseOrderType() {
        return new PurchaseOrderType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ShippingType }
     * 
     */
    public ShippingType createShippingType() {
        return new ShippingType();
    }

    /**
     * Create an instance of {@link OrderitemsType }
     * 
     */
    public OrderitemsType createOrderitemsType() {
        return new OrderitemsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PurchaseOrderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "porchese-Order")
    public JAXBElement<PurchaseOrderType> createPorcheseOrder(PurchaseOrderType value) {
        return new JAXBElement<PurchaseOrderType>(_PorcheseOrder_QNAME, PurchaseOrderType.class, null, value);
    }

}
