//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 09:49:37 AM IST 
//


package com.manash.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ticketInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ticketInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trainName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trainNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pnr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DOJ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bordingAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reservationUpto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ticketInfoType", propOrder = {
    "trainName",
    "trainNo",
    "pnr",
    "doj",
    "bordingAt",
    "reservationUpto"
})
public class TicketInfoType {

    @XmlElement(required = true)
    protected String trainName;
    @XmlElement(required = true)
    protected String trainNo;
    @XmlElement(required = true)
    protected String pnr;
    @XmlElement(name = "DOJ", required = true)
    protected String doj;
    @XmlElement(required = true)
    protected String bordingAt;
    @XmlElement(required = true)
    protected String reservationUpto;

    /**
     * Gets the value of the trainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainName() {
        return trainName;
    }

    /**
     * Sets the value of the trainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainName(String value) {
        this.trainName = value;
    }

    /**
     * Gets the value of the trainNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainNo() {
        return trainNo;
    }

    /**
     * Sets the value of the trainNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainNo(String value) {
        this.trainNo = value;
    }

    /**
     * Gets the value of the pnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPnr() {
        return pnr;
    }

    /**
     * Sets the value of the pnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPnr(String value) {
        this.pnr = value;
    }

    /**
     * Gets the value of the doj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOJ() {
        return doj;
    }

    /**
     * Sets the value of the doj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOJ(String value) {
        this.doj = value;
    }

    /**
     * Gets the value of the bordingAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBordingAt() {
        return bordingAt;
    }

    /**
     * Sets the value of the bordingAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBordingAt(String value) {
        this.bordingAt = value;
    }

    /**
     * Gets the value of the reservationUpto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationUpto() {
        return reservationUpto;
    }

    /**
     * Sets the value of the reservationUpto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationUpto(String value) {
        this.reservationUpto = value;
    }

}
